//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTS.BusinessEntity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=VTS_Development;Persist Sec" +
            "urity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=27.111.36.6\\production;Initial Catalog=SMSPortal;Persist Security Inf" +
            "o=True;User ID=smsportal")]
        public string SMSPortalConnectionString {
            get {
                return ((string)(this["SMSPortalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=VTS_Development;Persist Sec" +
            "urity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString1 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=VTS_Development;Persist Sec" +
            "urity Info=True;User ID=sa;Password=web@ccess.1")]
        public string VTS_DevelopmentConnectionString2 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=VTS_Development;Persist Sec" +
            "urity Info=True;User ID=JP")]
        public string VTS_DevelopmentConnectionString3 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=VTS_Development;Persist Sec" +
            "urity Info=True;User ID=JP;Password=password.1")]
        public string VTS_DevelopmentConnectionString4 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=27.111.36.30\\sqlexpress;Initial Catalog=VTS_Development;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString5 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=POLRI_DEV;Persist Security " +
            "Info=True;User ID=sa")]
        public string POLRI_DEVConnectionString {
            get {
                return ((string)(this["POLRI_DEVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=27.111.36.30\\SQLEXPRESS;Initial Catalog=VTS_Development;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString6 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=27.111.36.30\\SQLEXPRESS;Initial Catalog=VTS_Development;Persist Secur" +
            "ity Info=True;User ID=sa;Password=web@ccess.1")]
        public string VTS_DevelopmentConnectionString7 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.69.64.18\\production;Initial Catalog=VTS_Development;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString8 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=43.229.207.48\\production;Initial Catalog=VTS_LocalDev;User ID=sa")]
        public string VTS_LocalDevConnectionString {
            get {
                return ((string)(this["VTS_LocalDevConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=43.229.207.48\\production;Initial Catalog=VTS_LocalDev;User ID=sa")]
        public string VTS_LocalDevConnectionString1 {
            get {
                return ((string)(this["VTS_LocalDevConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=43.229.207.48\\production;Initial Catalog=VTS_Development;Persist Secu" +
            "rity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString9 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=43.229.207.48\\PRODUCTION;Initial Catalog=VTS_Development;Persist Secu" +
            "rity Info=True;User ID=sa")]
        public string VTS_DevelopmentConnectionString10 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=43.229.207.48\\PRODUCTION;Initial Catalog=VTS_Development;User ID=sa")]
        public string VTS_DevelopmentConnectionString11 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=43.229.207.48\\production;Initial Catalog=VTS_Development;Persist Secu" +
            "rity Info=True;User ID=sa;Password=web@ccess.1")]
        public string VTS_DevelopmentConnectionString12 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\DEVELOPMENT;Initial Catalog=VTS_Development;User ID=sa;" +
            "Password=web@ccess.1")]
        public string VTS_DevelopmentConnectionString13 {
            get {
                return ((string)(this["VTS_DevelopmentConnectionString13"]));
            }
        }
    }
}
